// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// ACH匯出紀錄
    /// </summary>
    public partial class Achrecord
    {
        /// <summary>
        /// RipFundAch1=往生第一筆,RipFundAch2=往生第二筆,FareAch=車馬
        /// </summary>
        public string FuncId { get; set; }
        /// <summary>
        /// 期數7碼或第一筆發放年月日
        /// </summary>
        public string IssueYm { get; set; }
        /// <summary>
        /// 交易序號6碼
        /// </summary>
        public string SeqNo { get; set; }
        /// <summary>
        /// 交易代號3碼
        /// </summary>
        public string TldcBank { get; set; }
        /// <summary>
        /// 發動者帳號
        /// </summary>
        public string TldcAcc { get; set; }
        /// <summary>
        /// 入帳銀行7碼(收受者銀行)
        /// </summary>
        public string PayeeBank { get; set; }
        /// <summary>
        /// 入帳帳號(收受者帳號)
        /// </summary>
        public string PayeeAcc { get; set; }
        /// <summary>
        /// 金額
        /// </summary>
        public decimal Amt { get; set; }
        /// <summary>
        /// 收受者身分證
        /// </summary>
        public string PayeeIdNo { get; set; }
        /// <summary>
        /// 服務人員姓名
        /// </summary>
        public string MemInfo4 { get; set; }
        /// <summary>
        /// 備註(第一筆公賻金/第二筆公賻金)
        /// </summary>
        public string Remark { get; set; }
        public string Creator { get; set; }
        public DateTime? CreateDate { get; set; }
        public string MemId { get; set; }
    }
}