// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 公告
    /// </summary>
    public partial class Announces
    {
        public int AnnounceRow { get; set; }
        /// <summary>
        /// 公告名稱
        /// </summary>
        public string AnnounceName { get; set; }
        /// <summary>
        /// 公告所屬月份
        /// </summary>
        public string Content { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateDate { get; set; }
    }
}