// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 銀行資料
    /// </summary>
    public partial class Bankinfo
    {
        /// <summary>
        /// 銀行代碼
        /// </summary>
        public string BankCode { get; set; }
        /// <summary>
        /// 銀行名稱
        /// </summary>
        public string BankName { get; set; }
        public string Creator { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}