// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 分會
    /// </summary>
    public partial class Branch
    {
        /// <summary>
        /// 所屬群組
        /// </summary>
        public string GrpId { get; set; }
        /// <summary>
        /// 區域
        /// </summary>
        public string AreaId { get; set; }
        /// <summary>
        /// 分會編號
        /// </summary>
        public string BranchId { get; set; }
        /// <summary>
        /// 分會名稱
        /// </summary>
        public string BranchName { get; set; }
        /// <summary>
        /// 分會督導
        /// </summary>
        public string BranchManager { get; set; }
        /// <summary>
        /// 是否領取職場補助
        /// </summary>
        public byte IsAllowance { get; set; }
        /// <summary>
        /// 領取職場補助服務人員ID
        /// </summary>
        public string AllowanceSevid { get; set; }
        /// <summary>
        /// 是否領取輔導補助
        /// </summary>
        public byte IsTutorAllowance { get; set; }
        /// <summary>
        /// 設立日
        /// </summary>
        public DateTime? EffectDate { get; set; }
        /// <summary>
        /// 裁撤日
        /// </summary>
        public DateTime? ExceptDate { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}