// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 系統參數代碼
    /// </summary>
    public partial class Codemaster
    {
        /// <summary>
        /// 代碼
        /// </summary>
        public string MasterKey { get; set; }
        /// <summary>
        /// 代碼名稱
        /// </summary>
        public string MasterName { get; set; }
        /// <summary>
        /// 代碼描述
        /// </summary>
        public string Description { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateDate { get; set; }
    }
}