// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 使用者操作紀錄(偏小,非重大功能操作)
    /// </summary>
    public partial class Execsmallrecord
    {
        public DateTime CreateDate { get; set; }
        public string FuncId { get; set; }
        public string IssueYm { get; set; }
        public string PayYm { get; set; }
        public string PayKind { get; set; }
        /// <summary>
        /// 1=成功,0=失敗
        /// </summary>
        public bool Result { get; set; }
        public uint? RowCount { get; set; }
        public uint? Cost1 { get; set; }
        public uint? Cost2 { get; set; }
        public string Creator { get; set; }
        /// <summary>
        /// 流水號(自動)
        /// </summary>
        public ulong Seq { get; set; }
        public string Remark { get; set; }
        public string Input { get; set; }
        public string ErrMessage { get; set; }
    }
}