// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 計算車馬費需要用到的前置table
    /// </summary>
    public partial class Faresource
    {
        /// <summary>
        /// 流水號
        /// </summary>
        public ulong Seq { get; set; }
        /// <summary>
        /// 期數yyyyMM2
        /// </summary>
        public string IssueYm { get; set; }
        /// <summary>
        /// 車馬費種類00/10/21/22一堆
        /// </summary>
        public string Ctype { get; set; }
        /// <summary>
        /// 繳費紀錄payId
        /// </summary>
        public string PayId { get; set; }
        /// <summary>
        /// 合併後的組別ABDH
        /// </summary>
        public string GrpId { get; set; }
        /// <summary>
        /// 分會後三碼
        /// </summary>
        public string Branch { get; set; }
        /// <summary>
        /// 該筆車馬來源的會員
        /// </summary>
        public string MemId { get; set; }
        /// <summary>
        /// 推薦人(服務人員編號)
        /// </summary>
        public string SevId { get; set; }
        /// <summary>
        /// SevId要對應orglist哪個欄位
        /// </summary>
        public string FieldName { get; set; }
        /// <summary>
        /// 會員繳費金額
        /// </summary>
        public decimal? PayAmt { get; set; }
        /// <summary>
        /// 車馬發放金額
        /// </summary>
        public decimal? Amt { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 執行車馬費計算的使用者
        /// </summary>
        public string Creator { get; set; }
        /// <summary>
        /// 車馬費計算的日期
        /// </summary>
        public DateTime? CreateDate { get; set; }
    }
}