// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 服務人員車馬費明細(官網)
    /// </summary>
    public partial class Farerpt
    {
        /// <summary>
        /// 結算年月yyyyMM2
        /// </summary>
        public string IssueYm { get; set; }
        /// <summary>
        /// 交易序號6碼
        /// </summary>
        public string SeqNo { get; set; }
        /// <summary>
        /// 交易代號3碼
        /// </summary>
        public string TldcBank { get; set; }
        /// <summary>
        /// 發動者帳號
        /// </summary>
        public string TldcAcc { get; set; }
        /// <summary>
        /// 入帳銀行7碼(收受者銀行)
        /// </summary>
        public string PayeeBank { get; set; }
        /// <summary>
        /// 入帳帳號(收受者帳號)
        /// </summary>
        public string PayeeAcc { get; set; }
        /// <summary>
        /// 金額
        /// </summary>
        public decimal? Amt { get; set; }
        /// <summary>
        /// 收受者身分證
        /// </summary>
        public string PayeeIdNo { get; set; }
        /// <summary>
        /// 收受者姓名
        /// </summary>
        public string PayeeName { get; set; }
        /// <summary>
        /// 撥款日期
        /// </summary>
        public string PayDate { get; set; }
        /// <summary>
        /// 期別
        /// </summary>
        public string MonthNo { get; set; }
        /// <summary>
        /// 服務人員編號
        /// </summary>
        public string SevId { get; set; }
        /// <summary>
        /// 服務人員身分證
        /// </summary>
        public string SevIdno { get; set; }
        /// <summary>
        /// 服務人員姓名
        /// </summary>
        public string SevName { get; set; }
        /// <summary>
        /// 入會日
        /// </summary>
        public DateTime? JoinDate { get; set; }
        /// <summary>
        /// 督導區
        /// </summary>
        public string BranchId { get; set; }
        /// <summary>
        /// 文書
        /// </summary>
        public string Amt10 { get; set; }
        /// <summary>
        /// 新件
        /// </summary>
        public string Amt00 { get; set; }
        /// <summary>
        /// 同階
        /// </summary>
        public string Amt21 { get; set; }
        /// <summary>
        /// 收件
        /// </summary>
        public string Amt50 { get; set; }
        /// <summary>
        /// 職場
        /// </summary>
        public string Amt55 { get; set; }
        /// <summary>
        /// 關懷
        /// </summary>
        public string Amt80 { get; set; }
        /// <summary>
        /// 協辦ABDH
        /// </summary>
        public string Amt70 { get; set; }
        /// <summary>
        /// 協辦A
        /// </summary>
        public string Amt701 { get; set; }
        /// <summary>
        /// 協辦B
        /// </summary>
        public string Amt702 { get; set; }
        /// <summary>
        /// 協辦D
        /// </summary>
        public string Amt703 { get; set; }
        /// <summary>
        /// 協辦H
        /// </summary>
        public string Amt704 { get; set; }
        /// <summary>
        /// 繳件
        /// </summary>
        public string Amt60 { get; set; }
        /// <summary>
        /// 處長繳件
        /// </summary>
        public string Amt40 { get; set; }
        /// <summary>
        /// 其他+1
        /// </summary>
        public string Other1 { get; set; }
        /// <summary>
        /// 其他+2
        /// </summary>
        public string Other2 { get; set; }
        /// <summary>
        /// 其他+3
        /// </summary>
        public string Other3 { get; set; }
        /// <summary>
        /// 其他+4
        /// </summary>
        public string Other4 { get; set; }
        /// <summary>
        /// 補車馬
        /// </summary>
        public string ExtraPay { get; set; }
        /// <summary>
        /// 代扣二代健保2%
        /// </summary>
        public string NoPay1 { get; set; }
        /// <summary>
        /// 代扣所得稅5%
        /// </summary>
        public string NoPay2 { get; set; }
        /// <summary>
        /// 扣車馬
        /// </summary>
        public string NoPay3 { get; set; }
        /// <summary>
        /// 扣年費
        /// </summary>
        public string NoPay4 { get; set; }
        /// <summary>
        /// 強制
        /// </summary>
        public string NoPay5 { get; set; }
        /// <summary>
        /// 其他-1
        /// </summary>
        public string NoPay6 { get; set; }
        /// <summary>
        /// 合計
        /// </summary>
        public string Total { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        public string Remark { get; set; }
        public string Creator { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}