// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 程式資訊
    /// </summary>
    public partial class Functable
    {
        /// <summary>
        /// 顯示順序
        /// </summary>
        public int? Order { get; set; }
        /// <summary>
        /// 程式ID
        /// </summary>
        public string FuncId { get; set; }
        /// <summary>
        /// 功能編號(for工程師)
        /// </summary>
        public string FuncType { get; set; }
        /// <summary>
        /// 程式名稱
        /// </summary>
        public string FuncName { get; set; }
        /// <summary>
        /// 啟用
        /// </summary>
        public bool? Enabled { get; set; }
        /// <summary>
        /// 是否顯示在menu
        /// </summary>
        public bool? InMenu { get; set; }
        /// <summary>
        /// 父層程式
        /// </summary>
        public string ParentFuncId { get; set; }
        /// <summary>
        /// 程式連結
        /// </summary>
        public string FuncUrl { get; set; }
        public string Creator { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateDate { get; set; }
    }
}