// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 程式權限設定
    /// </summary>
    public partial class Funcauthdetail
    {
        /// <summary>
        /// 權限設定ID
        /// </summary>
        public string FuncAuthId { get; set; }
        /// <summary>
        /// 程式ID
        /// </summary>
        public string FuncId { get; set; }
        /// <summary>
        /// 權限細節
        /// </summary>
        public string AuthDetail { get; set; }
        /// <summary>
        /// 細節描述
        /// </summary>
        public string DetailDesc { get; set; }
    }
}