// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// IP鎖定
    /// </summary>
    public partial class Iplock
    {
        public string LockId { get; set; }
        /// <summary>
        /// 是否鎖定
        /// </summary>
        public bool Enabled { get; set; }
        /// <summary>
        /// 登入日期
        /// </summary>
        public DateTime LoginDate { get; set; }
        /// <summary>
        /// 第五次失敗後的帳號
        /// </summary>
        public string Account { get; set; }
        /// <summary>
        /// 第五次失敗後的IP
        /// </summary>
        public string ClientIp { get; set; }
        /// <summary>
        /// 一堆雜資訊,用來細部判別登入者情況
        /// </summary>
        public string Session { get; set; }
        /// <summary>
        /// 瀏覽器版本
        /// </summary>
        public string Agent { get; set; }
        public int LogFailTimes { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}