// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 系統錯誤紀錄
    /// </summary>
    public partial class Logofexception
    {
        public string LogId { get; set; }
        /// <summary>
        /// 登入帳號
        /// </summary>
        public string OperId { get; set; }
        /// <summary>
        /// 錯誤類型
        /// </summary>
        public string ExceptionType { get; set; }
        /// <summary>
        /// 參數
        /// </summary>
        public string Params { get; set; }
        /// <summary>
        /// 錯誤信息
        /// </summary>
        public string ExceptionContent { get; set; }
        /// <summary>
        /// 錯誤詳細信息
        /// </summary>
        public string InnerException { get; set; }
        /// <summary>
        /// 發生時間
        /// </summary>
        public DateTime CreateDate { get; set; }
    }
}