// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 失格除會+升級降級(對應舊系統MEMBER_CHG)
    /// </summary>
    public partial class Logofpromote
    {
        /// <summary>
        /// 流水號(自動)
        /// </summary>
        public ulong Seq { get; set; }
        /// <summary>
        /// 異動日
        /// </summary>
        public DateTime ChangeDate { get; set; }
        /// <summary>
        /// memsevId
        /// </summary>
        public string MemsevId { get; set; }
        /// <summary>
        /// STAUS
        /// </summary>
        public string OldStatus { get; set; }
        /// <summary>
        /// oldBranch
        /// </summary>
        public string OldBranch { get; set; }
        /// <summary>
        /// oldJob
        /// </summary>
        public string OldJob { get; set; }
        /// <summary>
        /// oldPresevId
        /// </summary>
        public string OldPresevId { get; set; }
        /// <summary>
        /// CHG_TYPE
        /// </summary>
        public string NewStatus { get; set; }
        /// <summary>
        /// newBranch
        /// </summary>
        public string NewBranch { get; set; }
        /// <summary>
        /// newJob
        /// </summary>
        public string NewJob { get; set; }
        /// <summary>
        /// newPresevId
        /// </summary>
        public string NewPresevId { get; set; }
        /// <summary>
        /// (keep)會員M/服務人員V
        /// </summary>
        public string ChgKind { get; set; }
        /// <summary>
        /// (keep)
        /// </summary>
        public string IssueYm { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 審核人員(使用者ID)
        /// </summary>
        public string Reviewer { get; set; }
        /// <summary>
        /// 審核通過日
        /// </summary>
        public DateTime? ReviewDate { get; set; }
        public string Creator { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}