// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 公賻金
    /// </summary>
    public partial class Memripfund
    {
        /// <summary>
        /// 會員編號
        /// </summary>
        public string MemId { get; set; }
        /// <summary>
        /// 申請日
        /// </summary>
        public DateTime ApplyDate { get; set; }
        /// <summary>
        /// 往生日
        /// </summary>
        public DateTime Ripdate { get; set; }
        /// <summary>
        /// 往生所屬月份
        /// </summary>
        public string Ripmonth { get; set; }
        /// <summary>
        /// 年資月數(多存的)
        /// </summary>
        public ushort? Seniority { get; set; }
        /// <summary>
        /// 是否申請慰問金
        /// </summary>
        public bool? IsApply { get; set; }
        /// <summary>
        /// 領款方式
        /// </summary>
        public string PayType { get; set; }
        /// <summary>
        /// 身分證號(不要和單號搞混)
        /// </summary>
        public string PayId { get; set; }
        /// <summary>
        /// 銀行代號
        /// </summary>
        public string PayBankId { get; set; }
        /// <summary>
        /// 銀行帳號
        /// </summary>
        public string PayBankAcc { get; set; }
        /// <summary>
        /// 公賻金序號
        /// </summary>
        public string RipfundSn { get; set; }
        /// <summary>
        /// 往生原因
        /// </summary>
        public string Ripreason { get; set; }
        /// <summary>
        /// 第一筆金額
        /// </summary>
        public decimal? FirstAmt { get; set; }
        /// <summary>
        /// 第一筆發放日期
        /// </summary>
        public DateTime? FirstDate { get; set; }
        /// <summary>
        /// 第一筆簽回
        /// </summary>
        public byte? FirstSigningBack { get; set; }
        /// <summary>
        /// 第二筆金額
        /// </summary>
        public decimal? SecondAmt { get; set; }
        /// <summary>
        /// 第二筆發放日期
        /// </summary>
        public DateTime? SecondDate { get; set; }
        /// <summary>
        /// 第二筆簽回
        /// </summary>
        public byte? SecondSigningBack { get; set; }
        /// <summary>
        /// 第二筆確認人員
        /// </summary>
        public string SecondConfirm { get; set; }
        /// <summary>
        /// 第二筆倍率
        /// </summary>
        public decimal? SecondRatio { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 原有的會員狀態(刪除此單時用此欄位回復會員狀態)
        /// </summary>
        public string OriginStatus { get; set; }
        /// <summary>
        /// 逾期繳款金額
        /// </summary>
        public decimal? OverAmt { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}