// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 登入帳號主檔
    /// </summary>
    public partial class Oper
    {
        public string OperId { get; set; }
        /// <summary>
        /// 登入帳號
        /// </summary>
        public string OperAccount { get; set; }
        /// <summary>
        /// 登入者名稱
        /// </summary>
        public string OperName { get; set; }
        /// <summary>
        /// 密碼
        /// </summary>
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        /// <summary>
        /// 登入者群組
        /// </summary>
        public string OperGrpId { get; set; }
        public string CreateUser { get; set; }
        public DateTime CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateDate { get; set; }
    }
}