// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 群組權限
    /// </summary>
    public partial class Opergrprule
    {
        /// <summary>
        /// 流水號(自動)
        /// </summary>
        public ulong Seq { get; set; }
        /// <summary>
        /// 登入群組編號
        /// </summary>
        public string OperGrpId { get; set; }
        /// <summary>
        /// 程式權限編號
        /// </summary>
        public string FuncAuthId { get; set; }
    }
}