// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 繳費紀錄
    /// </summary>
    public partial class Payrecord
    {
        /// <summary>
        /// 繳費單號(非主KEY,互助年費填barcode2,新件取號)
        /// </summary>
        public string PayId { get; set; }
        /// <summary>
        /// 繳費月份
        /// </summary>
        public string PayYm { get; set; }
        /// <summary>
        /// 會員或服務人員編號
        /// </summary>
        public string MemId { get; set; }
        /// <summary>
        /// 繳費日期
        /// </summary>
        public DateTime PayDate { get; set; }
        /// <summary>
        /// 繳費項目
        /// </summary>
        public byte PayKind { get; set; }
        /// <summary>
        /// 繳費來源(地點)
        /// </summary>
        public string PaySource { get; set; }
        /// <summary>
        /// 繳費方式
        /// </summary>
        public string PayType { get; set; }
        /// <summary>
        /// 繳費方式說明(類似備註)
        /// </summary>
        public string PayMemo { get; set; }
        /// <summary>
        /// 繳費金額
        /// </summary>
        public decimal PayAmt { get; set; }
        /// <summary>
        /// 是否計算車馬費(PayKind=3才生效,正常=1,逾期為0)
        /// </summary>
        public bool? IsCalFare { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// null=正常,add=新增
        /// </summary>
        public string Status { get; set; }
        /// <summary>
        /// 送審人員(使用者ID)
        /// </summary>
        public string Sender { get; set; }
        /// <summary>
        /// 送審日
        /// </summary>
        public DateTime? SendDate { get; set; }
        /// <summary>
        /// 審核人員(使用者ID)
        /// </summary>
        public string Reviewer { get; set; }
        /// <summary>
        /// 審核通過日
        /// </summary>
        public DateTime? ReviewDate { get; set; }
        public string Creator { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }
        /// <summary>
        /// 如果有跑過一期車馬費,填入一期(此欄位有值就不能異動)
        /// </summary>
        public string IssueYm1 { get; set; }
        /// <summary>
        /// 如果有跑過二期車馬費,填入二期(此欄位有值就不能異動)
        /// </summary>
        public string IssueYm2 { get; set; }
    }
}