// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 繳費單
    /// </summary>
    public partial class Payslip
    {
        /// <summary>
        /// 繳費項目
        /// </summary>
        public byte PayKind { get; set; }
        /// <summary>
        /// 會員或服務人員編號
        /// </summary>
        public string MemId { get; set; }
        /// <summary>
        /// 本月月份
        /// </summary>
        public string PayYm { get; set; }
        /// <summary>
        /// 本月金額
        /// </summary>
        public decimal PayAmt { get; set; }
        /// <summary>
        /// 上月月份
        /// </summary>
        public string LastPayYm { get; set; }
        /// <summary>
        /// 上月金額
        /// </summary>
        public decimal? LastPayAmt { get; set; }
        /// <summary>
        /// 總計金額
        /// </summary>
        public decimal? TotalPayAmt { get; set; }
        /// <summary>
        /// 繳費期限
        /// </summary>
        public DateTime PayDeadline { get; set; }
        /// <summary>
        /// 條碼一
        /// </summary>
        public string Barcode1 { get; set; }
        /// <summary>
        /// 條碼二
        /// </summary>
        public string Barcode2 { get; set; }
        /// <summary>
        /// 條碼三
        /// </summary>
        public string Barcode3 { get; set; }
        /// <summary>
        /// 條碼四
        /// </summary>
        public string Barcode4 { get; set; }
        /// <summary>
        /// 條碼五
        /// </summary>
        public string Barcode5 { get; set; }
        /// <summary>
        /// 通知人郵遞區號
        /// </summary>
        public string NoticeZipCode { get; set; }
        /// <summary>
        /// 通知人完整地址
        /// </summary>
        public string NoticeAddress { get; set; }
        public string Creator { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }
        /// <summary>
        /// 該月第一次不用註記,之後產生的都押上年月(用在二次補單)
        /// </summary>
        public string SecondBillYm { get; set; }
    }
}