// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 各項車馬費ACH對應碼設定
    /// </summary>
    public partial class Settingfaretype
    {
        /// <summary>
        /// 代碼
        /// </summary>
        public string TypeId { get; set; }
        /// <summary>
        /// 車馬費項目
        /// </summary>
        public string TypeName { get; set; }
        /// <summary>
        /// ACH對照碼
        /// </summary>
        public string Ach { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        public string Remark { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}