// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 各組參數設定
    /// </summary>
    public partial class Settinggroup
    {
        public string ParamId { get; set; }
        /// <summary>
        /// 對應群組
        /// </summary>
        public string MemGrpId { get; set; }
        /// <summary>
        /// 項目代碼
        /// </summary>
        public string ItemCode { get; set; }
        /// <summary>
        /// 參數名稱
        /// </summary>
        public string ParamName { get; set; }
        /// <summary>
        /// 參數值
        /// </summary>
        public string ParamValue { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        public string Remark { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}