// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 月費設定
    /// </summary>
    public partial class Settingmonthlyfee
    {
        public string SetId { get; set; }
        public string MemGrpId { get; set; }
        /// <summary>
        /// 年(以內)
        /// </summary>
        public int YearWithin { get; set; }
        /// <summary>
        /// 金額
        /// </summary>
        public decimal Amt { get; set; }
        public string Remark { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateDate { get; set; }
    }
}