// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// XX資訊
    /// </summary>
    public partial class Settingtldc
    {
        /// <summary>
        /// 項目
        /// </summary>
        public string Item { get; set; }
        /// <summary>
        /// 項目名稱
        /// </summary>
        public string ItemName { get; set; }
        /// <summary>
        /// 值
        /// </summary>
        public string Value { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}