// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 服務人員主檔
    /// </summary>
    public partial class Sev
    {
        /// <summary>
        /// 會員編號
        /// </summary>
        public string SevId { get; set; }
        /// <summary>
        /// 會員姓名
        /// </summary>
        public string SevName { get; set; }
        /// <summary>
        /// 會員身分證號
        /// </summary>
        public string SevIdno { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        public string Status { get; set; }
        /// <summary>
        /// 組別
        /// </summary>
        public string GrpId { get; set; }
        /// <summary>
        /// 分會(會員4碼,服務3碼)
        /// </summary>
        public string BranchId { get; set; }
        /// <summary>
        /// 職等
        /// </summary>
        public string JobTitle { get; set; }
        /// <summary>
        /// 推薦人
        /// </summary>
        public string PreSevId { get; set; }
        /// <summary>
        /// 入會日
        /// </summary>
        public DateTime? JoinDate { get; set; }
        /// <summary>
        /// 除會日
        /// </summary>
        public DateTime? ExceptDate { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}