// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 服務人員轉讓申請紀錄9+13
    /// </summary>
    public partial class Sevtranrecord
    {
        /// <summary>
        /// 轉換日期
        /// </summary>
        public DateTime TranDate { get; set; }
        /// <summary>
        /// 服務人員
        /// </summary>
        public string SevId { get; set; }
        /// <summary>
        /// 申請日期
        /// </summary>
        public DateTime? ApplyDate { get; set; }
        /// <summary>
        /// 申請單號
        /// </summary>
        public string ApplySeq { get; set; }
        /// <summary>
        /// 車馬費補助費權益轉讓切結書
        /// </summary>
        public ulong? IsCutOff { get; set; }
        /// <summary>
        /// 補存摺影本
        /// </summary>
        public ulong? IsPassBookCopy { get; set; }
        /// <summary>
        /// 更改存摺帳號
        /// </summary>
        public ulong? IsChangeAcc { get; set; }
        /// <summary>
        /// 車馬費補助費權益轉讓切結書
        /// </summary>
        public ulong? IsRightDoc { get; set; }
        /// <summary>
        /// 各項車馬費補助費
        /// </summary>
        public ulong? IsCondole { get; set; }
        /// <summary>
        /// 關懷慰問金
        /// </summary>
        public ulong? IsAllowance { get; set; }
        /// <summary>
        /// 轉讓備註
        /// </summary>
        public string TranRemark { get; set; }
        /// <summary>
        /// 會員姓名
        /// </summary>
        public string SevName { get; set; }
        /// <summary>
        /// 會員身分證號
        /// </summary>
        public string SevIdno { get; set; }
        /// <summary>
        /// 生日
        /// </summary>
        public DateTime? Birthday { get; set; }
        /// <summary>
        /// 性別MF
        /// </summary>
        public string SexType { get; set; }
        /// <summary>
        /// 聯絡人
        /// </summary>
        public string ContName { get; set; }
        /// <summary>
        /// 手機1
        /// </summary>
        public string Mobile { get; set; }
        /// <summary>
        /// 手機2(會員不填)
        /// </summary>
        public string Mobile2 { get; set; }
        /// <summary>
        /// 電話
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// 電子郵箱
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 戶籍區號
        /// </summary>
        public string RegZipCode { get; set; }
        /// <summary>
        /// 戶籍地址
        /// </summary>
        public string RegAddress { get; set; }
        /// <summary>
        /// 通訊區號
        /// </summary>
        public string ZipCode { get; set; }
        /// <summary>
        /// 通訊地址
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// New會員姓名
        /// </summary>
        public string NewSevName { get; set; }
        /// <summary>
        /// New會員身分證號
        /// </summary>
        public string NewSevIdNo { get; set; }
        /// <summary>
        /// New生日
        /// </summary>
        public DateTime? NewBirthday { get; set; }
        /// <summary>
        /// New性別MF
        /// </summary>
        public string NewSexType { get; set; }
        /// <summary>
        /// New聯絡人
        /// </summary>
        public string NewContName { get; set; }
        /// <summary>
        /// New手機1
        /// </summary>
        public string NewMobile { get; set; }
        /// <summary>
        /// New手機2(會員不填)
        /// </summary>
        public string NewMobile2 { get; set; }
        /// <summary>
        /// New電話
        /// </summary>
        public string NewPhone { get; set; }
        /// <summary>
        /// New電子郵箱
        /// </summary>
        public string NewEmail { get; set; }
        /// <summary>
        /// New戶籍區號
        /// </summary>
        public string NewRegZipCode { get; set; }
        /// <summary>
        /// New戶籍地址
        /// </summary>
        public string NewRegAddress { get; set; }
        /// <summary>
        /// New通訊區號
        /// </summary>
        public string NewZipCode { get; set; }
        /// <summary>
        /// New通訊地址
        /// </summary>
        public string NewAddress { get; set; }
        public string Creator { get; set; }
        public DateTime CreateDate { get; set; }
    }
}