// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TldcFare.Dal
{
    /// <summary>
    /// 郵遞區號
    /// </summary>
    public partial class Zipcode
    {
        public string ZipCode1 { get; set; }
        public string Name { get; set; }
    }
}