export default {
    APP_INCREASE_LOADING_COUNTER: 'APP_INCREASE_LOADING_COUNTER',
    APP_DECREASE_LOADING_COUNTER: 'APP_DECREASE_LOADING_COUNTER',
    ISLOGIN: 'auth/ISLOGIN',
    TOKEN: 'auth/TOKEN',
    LANG: 'auth/LANG',
    OPERID: 'auth/OPERID',
    OPERNAME: 'auth/OPERNAME',
    LOADING: 'LOADING',
    
    ALLBRANCH: 'ALLBRANCH',
    AVAILBRANCH: 'AVAILBRANCH',
    ALLSEV: 'ALLSEV',
    AVAILSEV: 'AVAILSEV',
    
    MEMGRPS: 'MEMGRPS',
    MEMSTATUS: 'MEMSTATUS',
    MEMSEXTYPIES: 'MEMSEXTYPIES',
    KEYOPERS: 'KEYOPERS',
    POSTCODE: 'POSTCODE',
    
    PAYKIND: 'PAYKIND',
    PAYSOURCE: 'PAYSOURCE',
    PAYTYPE: 'PAYTYPE',
}